import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Caveat, Libre_Baskerville } from "next/font/google";


const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
})

const libreBaskervilleNormal = Libre_Baskerville({
  subsets: ["latin"],
  variable: "--font-libre-baskerville-normal",
  weight: "400"
})
const libreBaskervilleBold = Libre_Baskerville({
  subsets: ["latin"],
  variable: "--font-libre-baskerville-bold",
  weight: "700"
})



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${caveat.variable} ${libreBaskervilleNormal.variable} ${libreBaskervilleBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
